---
title: "Client Report - What's in a Name?"
subtitle: "Course DS 250"
author: "Dallin Moak"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


## Project Notes

__For Project 1 the answer to each question should include a chart **and** a written response. The years labels on your charts should not include a comma. At least **two** of your charts must include reference marks.__  

```{python}
import os

os.getcwd()
from p1_source import myNamePlotData

myNamePlotData
```

## QUESTION|TASK 1

__How does your name at your birth year compare to its use historically?__

_my name, "Dallin" occured most about 3 years after I was born, but the name had been trending up from obscurity for almost 8 years before my birth in 1996.

```{python}
from p1_source import myNamePlot

myNamePlot
```


## QUESTION|TASK 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

_The dataset indicates that Britanys of age 35 (in 2025) are most common.There are very few people by that name older than 50, and only a few younger than 19._

```{python}

from p1_source import brittanyPlot

brittanyPlot

```


## QUESTION|TASK 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names in a single chart. What trends do you notice?__

_all names have a dip starting after about 1925, and a massive boom during the war years, with a peak after the end of the war._

```{python}
from p1_source import q3DataPlot
q3DataPlot

```
_this graph attempts to normalize the data relative to their frequency in 1920. they seem to follow a really similar pattern, but with peter being the most strongly affected_
```{python}
from p1_source import q3DataPlotAlt
q3DataPlotAlt
```
## QUESTION|TASK 4

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__  

_type your results and analysis here_

```{python}
# Include and execute your code here


```

---

## STRETCH QUESTION|TASK 1

__Reproduce the chart Elliot using the data from the `names_year.csv` file.__ 

_type your results and analysis here_

```{python}
# Include and execute your code here


```


---
